### ISSUE TITLE
ARM64 vs. x86_64 Benchmark test

### ISSUE THREAD

**Issue by Maleware** [stackabletech/docker-images#586]
As we teamed up with HPE & Ampere and present our results of porting SDP to ARM64 at Cloudfest, we want to benchmark the capabilities to create evidence of the strength of ARM64.

For this we plan to do:

- [x] Provision two comparable clusters one on ARM64 and one on x86_64
    - Ressource suggestion: `cpu: 30 , mem: 70 Gi` on Azure
    - TODO: A good fit for x86_64 cpu
- [x] come up with an test which benchmarks the computing power of both archs
    - Suggestion for Benchmark test: https://www.tpc.org/tpch/
    - This tests only cpu power and requires us only to have Trino
    - TODO: Find a good set of queries out of the one published. 
- [x] Testruns and evaluation

**Comment by Maleware** [comment]
So far the results of the Benchmarktest.

We did three in total, one where data generated will be stored in RAM and queried from there, then one where one query is running and data get generated on the fly. The last one uses data generation while querying too, but has 10 queries in parallel to max out cpu.

`Test with RAM data`
<ul>
  <li><code>Pre-requisits</code> (Test with memory connector and store gen data in mem)</li>
  <ul>
    <li>Creating data:</li>
    <li>
      <pre data-lang="bash">	  CREATE SCHEMA memory.tpch;
	      -&gt; 
	      -&gt; use memory.tpch;
	      -&gt; 
	      -&gt; -- create table nation as select * from tpch.sf5.nation;
	      -&gt; -- create table region as select * from tpch.sf5.region;
	      -&gt; -- create table part as select * from tpch.sf5.part;
	      -&gt; -- create table partsupp as select * from tpch.sf5.partsupp;
	      -&gt; -- create table supplier as select * from tpch.sf5.supplier;
	      -&gt; -- create table customer as select * from tpch.sf5.customer;
	      -&gt; -- create table orders as select * from tpch.sf5.orders;
	      -&gt; create table lineitem as select * from tpch.sf15.lineitem;
</pre>
    </li>
    <li>Query:</li>
    <li>
      <pre data-lang="bash">	  select
	           -&gt; returnflag,
	           -&gt; linestatus,
	           -&gt; sum(quantity) as sum_qty,
	           -&gt; sum(extendedprice) as sum_base_price,
	           -&gt; sum(extendedprice*(1-discount)) as sum_disc_price,
	           -&gt; sum(extendedprice*(1-discount)*(1+tax)) as sum_charge,
	           -&gt; avg(quantity) as avg_qty,
	           -&gt; avg(extendedprice) as avg_price,
	           -&gt; avg(discount) as avg_disc,
	           -&gt; count(*) as count_order
	           -&gt; from lineitem
	           -&gt; group by returnflag, linestatus 
	           -&gt; order by returnflag, linestatus;
</pre>
    </li>
  </ul>
  <li>
    <code>Intel</code>
  </li>
  <ul>
    <li>
      <pre data-lang="bash">	  CREATE SCHEMA
	  USE
	  CREATE TABLE: 89987373 rows
	  
	  Query 20240319_051120_00004_sxvxv, FINISHED, 2 nodes
	  Splits: 26 total, 26 done (100.00%)
	  26.80 [90M rows, 0B] [3.36M rows/s, 0B/s]
</pre>
    </li>
    <li>
      <pre data-lang="bash">	  Query 20240319_051942_00006_sxvxv, FINISHED, 1 node
	  Splits: 54 total, 54 done (100.00%)
	  2.31 [90M rows, 4.02GB] [39M rows/s, 1.75GB/s]
</pre>
    </li>
  </ul>
  <li>
    <code>AMD EPYC</code>
  </li>
  <ul>
    <li>
      <pre data-lang="bash">	  CREATE SCHEMA
	  USE
	  CREATE TABLE: 89987373 rows
	  
	  Query 20240319_051120_00003_rfbuk, FINISHED, 2 nodes
	  Splits: 26 total, 26 done (100.00%)
	  29.32 [90M rows, 0B] [3.07M rows/s, 0B/s]
</pre>
    </li>
    <li>
      <pre data-lang="bash">	  Query 20240319_052001_00006_rfbuk, FINISHED, 1 node
	  Splits: 54 total, 54 done (100.00%)
	  2.47 [90M rows, 4.02GB] [36.5M rows/s, 1.63GB/s]
</pre>
    </li>
  </ul>
  <li>
    <code>Ampere Altra</code>
  </li>
  <ul>
    <li>
      <pre data-lang="bash">	  CREATE SCHEMA
	  USE
	  CREATE TABLE: 89987373 rows
	  
	  Query 20240319_055233_00003_8pscd, FINISHED, 2 nodes
	  Splits: 42 total, 42 done (100.00%)
	  35.47 [90M rows, 0B] [2.54M rows/s, 0B/s]
</pre>
    </li>
    <li>
      <pre data-lang="bash">	  Query 20240319_055341_00006_8pscd, FINISHED, 1 node
	  Splits: 102 total, 102 done (100.00%)
	  3.54 [90M rows, 4.02GB] [25.4M rows/s, 1.14GB/s]
</pre>
    </li>
    <li>
      <code>Results</code>
    </li>
    <ul>
      <li>CPU Power / Euro</li>
      <li>
        
Vendor | Architecture | Cost per month | Cost per compute power
-- | -- | -- | --
AMD EPYC | AMD64 | 1,137.05 | CPM / 1.63GB/s  = 697,5767
Intel Ice Lake | x86_64 | 1,486.91 | CPM / 1.75GB/s = 849,6629
Ampere Altra | ARM64 | 1,191.72 | CPM / 1.14GB/s  = 1045,3684


      </li>
    </ul>
  </ul>
</ul>

**Comment by Maleware** [comment]
- `Pre-requisits` (sf.100 - Data gets generated on the fly and queried)
	- `Catalog`
		-
		  ```bash
		   use tpch.sf100;
		  ```
	- `Query`
		-
		  ```
		  trino:sf100> select
		            -> returnflag,
		            -> linestatus,
		            -> sum(quantity) as sum_qty,
		            -> sum(extendedprice) as sum_base_price,
		            -> sum(extendedprice*(1-discount)) as sum_disc_price,
		            -> sum(extendedprice*(1-discount)*(1+tax)) as sum_charge,
		            -> avg(quantity) as avg_qty,
		            -> avg(extendedprice) as avg_price,
		            -> avg(discount) as avg_disc,
		            -> count(*) as count_order
		            -> from lineitem
		            -> group by returnflag, linestatus 
		            -> order by returnflag, linestatus;
		  ```
- `Intel Ice Lake`
	-
	  ```Bash
	  Query 20240319_060117_00011_sxvxv, FINISHED, 1 node
	  Splits: 54 total, 54 done (100.00%)
	  1:31 [600M rows, 0B] [6.59M rows/s, 0B/s]
	  ```
- `AMD EPYC`
	-
	  ```bash
	  Query 20240319_060119_00011_rfbuk, FINISHED, 1 node
	  Splits: 54 total, 54 done (100.00%)
	  1:38 [600M rows, 0B] [6.12M rows/s, 0B/s]
	  ```
- `Ampere Altra`
	-
	  ```bash
	  Query 20240319_060116_00012_8pscd, FINISHED, 1 node
	  Splits: 102 total, 102 done (100.00%)
	  1:48 [600M rows, 0B] [5.55M rows/s, 0B/s]
	  ```

**Comment by Maleware** [comment]
<ul>
  <li>
    <code>Pre-requisits</code>
  </li>
  <li>
    <code>Query</code>
  </li>
  <ul>
    <li>
      <pre data-lang="bash">	  trino:sf100&gt; select
	            -&gt; returnflag,
	            -&gt; linestatus,
	            -&gt; sum(quantity) as sum_qty,
	            -&gt; sum(extendedprice) as sum_base_price,
	            -&gt; sum(extendedprice*(1-discount)) as sum_disc_price,
	            -&gt; sum(extendedprice*(1-discount)*(1+tax)) as sum_charge,
	            -&gt; avg(quantity) as avg_qty,
	            -&gt; avg(extendedprice) as avg_price,
	            -&gt; avg(discount) as avg_disc,
	            -&gt; count(*) as count_order
	            -&gt; from lineitem
	            -&gt; group by returnflag, linestatus 
	            -&gt; order by returnflag, linestatus;
</pre>
    </li>
  </ul>
  <li>
    <code>Concept</code>
  </li>
  <ul>
    <li>This query is going to be executed in parallel 10 times. The average will be the result as well as min and max</li>
  </ul>
  <li>
    <code>Intel Ice Lake</code>
  </li>
  <ul>
    <li>
      
Average Query time | Minimum | Maximum
-- | -- | --
3,257 | 3.20m | 3.32m


    </li>
  </ul>
</ul>

**Comment by Maleware** [comment]
Trino Manifest:
```
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: tpc-h-trino
  namespace: tpc
spec:
  image:
    productVersion: "428"
    custom: docker.stackable.tech/stackable-experimental/trino:428-stackable23.11.0
  clusterConfig:
    catalogLabelSelector:
      matchLabels:
        trino: tpc-h-trino
    listenerClass: external-unstable
  coordinators:
    config:
      resources:
        cpu:
          min: "4"
          max: "4"
        memory:
          limit: 6Gi
    roleGroups:
      default:
        replicas: 1
  workers:
    config:
      resources:
        cpu:
          min: "24"
          max: "24"
        memory:
          limit: 50Gi
    roleGroups:
      default:
        replicas: 1

---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  # The name of the catalog as it will appear in Trino
  name: tpch
  namespace: tpc
  # TrinoCluster can use these labels to select which catalogs to include
  labels:
    trino: tpc-h-trino
spec:
  connector:
    tpch: {} # No options needed
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: memory
  labels:
    trino: tpc-h-trino
  namespace: tpc
spec:
  connector:
    generic:
      connectorName: memory
      properties:
        memory.max-data-per-node:
          value: 20GB
```
