### ISSUE TITLE
Replace versions.py with a TOML file

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/docker-images#770]
We currently track supported product versions and dependencies in a `versions.py` file (which is imported by the `conf.py` in the root of the repo, which is in turn imported by [`bake`].

Ideally, configurations should be static which would also simplify how this is imported.

Ultimately, [`bake`] could then be upgraded to not import a conf.py but rather load in TOML configurations.

> [!NOTE]
> [`bake`] is still required for builds as it constructs a dependency graph and builds them before

[`bake`]: https://github.com/stackabletech/image-tools

**Comment by NickLarsenNZ** [comment]
Nice, I like the options. I'm also torn. I like both the `.versions` bit but also like products (a faux key) being hoisted up.

**Comment by razvan** [comment]
+1 for switching from `.py` to `.toml`
-1 for managing multiple releases in `main`. We already have `release-*` branches that my contain much more than just versions. These would clash and make maintenance harder.

**Comment by Techassi** [comment]
>-1 for managing multiple releases in main. We already have release-* branches that may contain much more than just versions. These would clash and make maintenance harder.

To be honest, I'm not a huge fan of release branches as they can often be hard to work with. But I can understand, why we want to keep the current workflow and how tracking Stackable releases in multiple places will cause pain points later down the road.

An alternative syntax could look like this:

```toml
[versions."2.8.3"]
dependencies = { python = "3.9", vector = "0.39.0" }

# Identical to above, just an alternate way of writing
[versions."3.0.0".dependencies]
python = "3.11"
vector = "0.39.0"
```

<details>
<summary>JSON structure</summary>

```json
{
  "versions": {
    "2.8.3": {
      "dependencies": {
        "python": "3.9",
        "vector": "0.39.0"
      }
    },
    "3.0.0": {
      "dependencies": {
        "python": "3.11",
        "vector": "0.39.0"
      }
    }
  }
}
```

</details>

---

Switching off release branches is completely out of scope of this issue, so let's discuss that at a later point.

**Comment by NickLarsenNZ** [comment]
As part of the work to test container images on PRs, we would like a flag to mark which versions should be included in tests. Extending @Techassi's example from above, this could look like:

```toml
[versions."2.8.3"]
dependencies = { python = "3.9", vector = "0.39.0" }
build_on_pr = true
```

`build_on_pr` would be optional, and default to `false`.
